os:
  - linux
services:
  - docker
language: java
jdk:
  - oraclejdk8
node_js:
  - "6.9.1"
sudo: true
cache:
  directories:
    - $HOME/.m2
    - $HOME/.yarn-cache
env:
  - NODE_VERSION=6.9.1
before_install:
  - sudo /etc/init.d/mysql stop
  - nvm install $NODE_VERSION
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add bower gulp-cli
  - node -v
  - npm -v
  - bower -v
  - gulp -v
  - java -version
install: yarn
script:
  # - ./mvnw clean
  # - ./mvnw test
  # - gulp test
  # - ./mvnw package -Pprod -DskipTests
  - docker-compose -f src/main/docker/mysql.yml up -d
  - docker ps -a
  - ./mvnw clean package -Pprod -DskipTests
  - java -jar target/*.war --spring.profiles.active=prod &
  - sleep 60
  - curl -v http://localhost:8080
