os:
  - linux
services:
  - docker
language: java
node_js:
  - "6.9.1"
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.m2
    - $HOME/.yarn-cache
env:
  - NODE_VERSION=6.9.1
before_install:
  - nvm install $NODE_VERSION
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add yo bower gulp-cli
  - node -v
  - npm -v
  - bower -v
  - gulp -v
  - java -version
install: yarn
script:
  # - ./mvnw clean
  # - ./mvnw test
  # - gulp test
  # - ./mvnw package -Pprod -DskipTests
  - ./mvnw clean package -DskipTests
  - java -jar target/*.war
  - sleep -60
  - curl -v http://localhost:8080
